apiVersion: v1
kind: Service
metadata:
  labels:
    app: dotnet-deploy
  name: devfile-dotnet-deploy
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: devfile-dotnet-deploy
  type: LoadBalancer

